SET lock_timeout = '5s';

-- ==========================================================================
-- Worker control plane: one row per worker for admin start/stop/concurrency
-- ==========================================================================

CREATE TABLE IF NOT EXISTS public.worker_control (
    worker_id text PRIMARY KEY,
    registered_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    status_desired text NOT NULL DEFAULT 'idle'
        CHECK (status_desired IN ('idle', 'running', 'paused', 'stopping')),
    status_actual text NOT NULL DEFAULT 'idle'
        CHECK (status_actual IN ('idle', 'running', 'paused', 'stopping', 'degraded')),
    desired_concurrency integer NOT NULL DEFAULT 0
        CHECK (desired_concurrency >= 0 AND desired_concurrency <= 1000),
    current_jobs integer NOT NULL DEFAULT 0
        CHECK (current_jobs >= 0),
    current_ip text DEFAULT NULL,
    cpu_pct numeric(5,2) DEFAULT NULL
        CHECK (cpu_pct IS NULL OR (cpu_pct >= 0 AND cpu_pct <= 100)),
    ram_pct numeric(5,2) DEFAULT NULL
        CHECK (ram_pct IS NULL OR (ram_pct >= 0 AND ram_pct <= 100)),
    disk_pct numeric(5,2) DEFAULT NULL
        CHECK (disk_pct IS NULL OR (disk_pct >= 0 AND disk_pct <= 100)),
    hostname text DEFAULT NULL,
    version text DEFAULT NULL,
    last_error_message text DEFAULT NULL,
    desired_updated_at timestamptz DEFAULT NULL,
    desired_updated_by uuid DEFAULT NULL,
    stats_updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.worker_control IS
    'Per-worker control and heartbeat state for admin-driven enrichment orchestration.';
COMMENT ON COLUMN public.worker_control.worker_id IS 'Stable worker identifier generated by the worker process at startup.';
COMMENT ON COLUMN public.worker_control.status_desired IS 'Admin-requested worker state.';
COMMENT ON COLUMN public.worker_control.status_actual IS 'Worker-reported current runtime state.';
COMMENT ON COLUMN public.worker_control.desired_concurrency IS 'Admin-requested max in-flight enrichments for this worker.';
COMMENT ON COLUMN public.worker_control.current_jobs IS 'Worker-reported number of currently active enrichments.';
COMMENT ON COLUMN public.worker_control.current_ip IS 'Current worker IP address as reported by the worker.';
COMMENT ON COLUMN public.worker_control.stats_updated_at IS 'Timestamp of the latest worker heartbeat payload.';

CREATE INDEX IF NOT EXISTS idx_worker_control_last_seen_at
    ON public.worker_control (last_seen_at DESC);

CREATE INDEX IF NOT EXISTS idx_worker_control_status_actual
    ON public.worker_control (status_actual);

-- ==========================================================================
-- Aggregated worker LLM usage buckets for admin time-window reporting
-- ==========================================================================

CREATE TABLE IF NOT EXISTS public.worker_llm_usage (
    bucket_start timestamptz NOT NULL,
    worker_id text NOT NULL,
    input_tokens bigint NOT NULL DEFAULT 0 CHECK (input_tokens >= 0),
    output_tokens bigint NOT NULL DEFAULT 0 CHECK (output_tokens >= 0),
    request_count integer NOT NULL DEFAULT 0 CHECK (request_count >= 0),
    success_count integer NOT NULL DEFAULT 0 CHECK (success_count >= 0),
    failure_count integer NOT NULL DEFAULT 0 CHECK (failure_count >= 0),
    CONSTRAINT worker_llm_usage_pkey PRIMARY KEY (bucket_start, worker_id),
    CONSTRAINT worker_llm_usage_worker_id_fkey
        FOREIGN KEY (worker_id) REFERENCES public.worker_control(worker_id) ON DELETE CASCADE
);

COMMENT ON TABLE public.worker_llm_usage IS
    'Time-bucketed aggregated LLM usage counters per worker for 1h/1d/7d admin metrics.';
COMMENT ON COLUMN public.worker_llm_usage.bucket_start IS 'Start time of the aggregation bucket (recommended: 5-minute bucket).' ;
COMMENT ON COLUMN public.worker_llm_usage.worker_id IS 'Worker that produced the aggregated usage.';

CREATE INDEX IF NOT EXISTS idx_worker_llm_usage_worker_bucket
    ON public.worker_llm_usage (worker_id, bucket_start DESC);

CREATE INDEX IF NOT EXISTS idx_worker_llm_usage_bucket_start
    ON public.worker_llm_usage (bucket_start DESC);

-- ==========================================================================
-- Internal per-place claim/retry state for multi-worker enrichment orchestration
-- ==========================================================================

CREATE TABLE IF NOT EXISTS public.place_llm_enrichment_state (
    place_id bigint PRIMARY KEY,
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'running', 'retry_wait', 'succeeded', 'failed_permanent')),
    claimed_by_worker_id text DEFAULT NULL,
    claim_token uuid DEFAULT NULL,
    claim_expires_at timestamptz DEFAULT NULL,
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    last_attempt_at timestamptz DEFAULT NULL,
    last_succeeded_at timestamptz DEFAULT NULL,
    next_retry_at timestamptz DEFAULT NULL,
    last_error_classification text DEFAULT NULL,
    last_error_message text DEFAULT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT place_llm_enrichment_state_place_id_fkey
        FOREIGN KEY (place_id) REFERENCES public.places(id) ON DELETE CASCADE,
    CONSTRAINT place_llm_enrichment_state_worker_id_fkey
        FOREIGN KEY (claimed_by_worker_id) REFERENCES public.worker_control(worker_id) ON DELETE SET NULL
);

COMMENT ON TABLE public.place_llm_enrichment_state IS
    'Internal per-place enrichment state used for safe multi-worker claiming, leases, and retries.';
COMMENT ON COLUMN public.place_llm_enrichment_state.status IS 'Operational enrichment state for this place.';
COMMENT ON COLUMN public.place_llm_enrichment_state.claim_token IS 'Opaque lease token used to validate heartbeat/complete/fail updates.';
COMMENT ON COLUMN public.place_llm_enrichment_state.claim_expires_at IS 'Lease expiry timestamp after which the place can be reclaimed.';

CREATE INDEX IF NOT EXISTS idx_place_llm_enrichment_state_claimable
    ON public.place_llm_enrichment_state (status, next_retry_at, claim_expires_at);

CREATE INDEX IF NOT EXISTS idx_place_llm_enrichment_state_claimed_by_worker
    ON public.place_llm_enrichment_state (claimed_by_worker_id);

CREATE INDEX IF NOT EXISTS idx_place_llm_enrichment_state_updated_at
    ON public.place_llm_enrichment_state (updated_at DESC);

-- ==========================================================================
-- Extend place_llm_properties for admin metrics and worker attribution
-- ==========================================================================

ALTER TABLE public.place_llm_properties
    ADD COLUMN IF NOT EXISTS last_enriched_at timestamptz DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS coverage_score numeric(5,4) DEFAULT NULL
        CHECK (coverage_score IS NULL OR (coverage_score >= 0 AND coverage_score <= 1)),
    ADD COLUMN IF NOT EXISTS last_worker_id text DEFAULT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'place_llm_properties_last_worker_id_fkey'
          AND conrelid = 'public.place_llm_properties'::regclass
    ) THEN
        ALTER TABLE public.place_llm_properties
            ADD CONSTRAINT place_llm_properties_last_worker_id_fkey
            FOREIGN KEY (last_worker_id) REFERENCES public.worker_control(worker_id) ON DELETE SET NULL;
    END IF;
END $$;

COMMENT ON COLUMN public.place_llm_properties.last_enriched_at IS
    'Timestamp of the most recent successful LLM enrichment write for this place.';
COMMENT ON COLUMN public.place_llm_properties.coverage_score IS
    'Normalized LLM enrichment coverage score in the range 0..1.';
COMMENT ON COLUMN public.place_llm_properties.last_worker_id IS
    'Worker that most recently wrote the successful LLM properties row.';

CREATE INDEX IF NOT EXISTS idx_place_llm_properties_last_enriched_at
    ON public.place_llm_properties (last_enriched_at DESC);

CREATE INDEX IF NOT EXISTS idx_place_llm_properties_last_worker_id
    ON public.place_llm_properties (last_worker_id);

-- ==========================================================================
-- Row level security: service role only
-- ==========================================================================

ALTER TABLE public.worker_control ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.worker_llm_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.place_llm_enrichment_state ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'worker_control'
          AND policyname = 'Service role can manage worker control'
    ) THEN
        EXECUTE 'CREATE POLICY "Service role can manage worker control" ON public.worker_control FOR ALL USING (auth.role() = ''service_role'') WITH CHECK (auth.role() = ''service_role'')';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'worker_llm_usage'
          AND policyname = 'Service role can manage worker llm usage'
    ) THEN
        EXECUTE 'CREATE POLICY "Service role can manage worker llm usage" ON public.worker_llm_usage FOR ALL USING (auth.role() = ''service_role'') WITH CHECK (auth.role() = ''service_role'')';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'place_llm_enrichment_state'
          AND policyname = 'Service role can manage place llm enrichment state'
    ) THEN
        EXECUTE 'CREATE POLICY "Service role can manage place llm enrichment state" ON public.place_llm_enrichment_state FOR ALL USING (auth.role() = ''service_role'') WITH CHECK (auth.role() = ''service_role'')';
    END IF;
END $$;
