-- ============================================================================
-- Migration: Add Source Family Tables and Runtime Fields
-- Date: 2026-03-16
-- Purpose: Phase 1 - Add normalized source-family tables and child tables
--          with proper constraints, indexes, and FKs
-- ============================================================================

-- ============================================================================
-- PART 1: Add Runtime Fields to place_enrichment
-- ============================================================================

-- These 7 fields move from runtime-only to formal schema (additive-only)
ALTER TABLE IF EXISTS place_enrichment
    ADD COLUMN IF NOT EXISTS source_evidence jsonb DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS evidence_markers jsonb DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS collection_status text DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS failure_classification text DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS provider_attempts jsonb DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS job_cost_usd numeric(10,4) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS enrichment_schema_version text DEFAULT NULL;

-- Add comment documenting the purpose of each new field
COMMENT ON COLUMN place_enrichment.source_evidence IS 
    'JSONB evidence collection from sources (allowed: evidence storage per JSONB minimization rule)';
COMMENT ON COLUMN place_enrichment.evidence_markers IS 
    'JSONB trust markers for validation (allowed: evidence storage per JSONB minimization rule)';
COMMENT ON COLUMN place_enrichment.collection_status IS 
    'Status of evidence collection: pending, processing, completed, failed';
COMMENT ON COLUMN place_enrichment.failure_classification IS 
    'Error categorization for failed enrichment attempts';
COMMENT ON COLUMN place_enrichment.provider_attempts IS 
    'JSONB tracking of provider retry attempts (allowed: debug metadata)';
COMMENT ON COLUMN place_enrichment.job_cost_usd IS 
    'Total cost of enrichment job in USD (note: duplicates cost_usd - consolidation in Phase 2)';
COMMENT ON COLUMN place_enrichment.enrichment_schema_version IS 
    'Schema version for tracking migration progress';

-- ============================================================================
-- PART 2: Create Parent Tables
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 2.1 place_llm_enrichments: LLM output storage (Derived source family)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS place_llm_enrichments (
    id bigserial PRIMARY KEY,
    place_id bigint NOT NULL,
    job_id bigint,
    provider text NOT NULL,
    model text NOT NULL,
    prompt_version text,
    summary_de text,
    confidence numeric(3,2) CHECK (confidence >= 0 AND confidence <= 1),
    hallucination_risk numeric(3,2) CHECK (hallucination_risk >= 0 AND hallucination_risk <= 1),
    token_input integer,
    token_output integer,
    cost_usd numeric(10,4),
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
    started_at timestamptz,
    completed_at timestamptz,
    is_current boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid DEFAULT auth.uid(),
    
    -- Foreign key to places table
    CONSTRAINT fk_place_llm_enrichments_place 
        FOREIGN KEY (place_id) REFERENCES places(id) ON DELETE CASCADE
);

COMMENT ON TABLE place_llm_enrichments IS 
    'LLM enrichment outputs - Derived source family per Source-Completeness Rule';
COMMENT ON COLUMN place_llm_enrichments.place_id IS 'Reference to places.id';
COMMENT ON COLUMN place_llm_enrichments.job_id IS 'Reference to enrichment_jobs.id';
COMMENT ON COLUMN place_llm_enrichments.provider IS 'LLM provider (openai, anthropic, etc.)';
COMMENT ON COLUMN place_llm_enrichments.model IS 'Model identifier (gpt-4, claude-3, etc.)';
COMMENT ON COLUMN place_llm_enrichments.summary_de IS 'German summary generated by LLM';
COMMENT ON COLUMN place_llm_enrichments.is_current IS 'Whether this is the current/valid enrichment';

-- ----------------------------------------------------------------------------
-- 2.2 place_source_evidence_runs: Evidence collection audit trail
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS place_source_evidence_runs (
    id bigserial PRIMARY KEY,
    place_id bigint NOT NULL,
    job_id bigint,
    worker_id text,
    attempt_number integer NOT NULL DEFAULT 1 CHECK (attempt_number > 0),
    collection_status text NOT NULL DEFAULT 'pending' 
        CHECK (collection_status IN ('pending', 'processing', 'completed', 'failed')),
    source_urls jsonb DEFAULT '[]'::jsonb,
    source_evidence jsonb DEFAULT '{}'::jsonb,
    evidence_markers jsonb DEFAULT '{}'::jsonb,
    trusted_source_count integer DEFAULT 0 CHECK (trusted_source_count >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    
    -- Foreign key to places table
    CONSTRAINT fk_evidence_runs_place 
        FOREIGN KEY (place_id) REFERENCES places(id) ON DELETE CASCADE
);

COMMENT ON TABLE place_source_evidence_runs IS 
    'Evidence collection audit trail - Scraped/Derived source family per Source-Completeness Rule';
COMMENT ON COLUMN place_source_evidence_runs.place_id IS 'Reference to places.id';
COMMENT ON COLUMN place_source_evidence_runs.job_id IS 'Reference to enrichment_jobs.id';
COMMENT ON COLUMN place_source_evidence_runs.worker_id IS 'Worker that performed collection';
COMMENT ON COLUMN place_source_evidence_runs.attempt_number IS 'Retry attempt number';
COMMENT ON COLUMN place_source_evidence_runs.collection_status IS 'Overall status of evidence collection';
COMMENT ON COLUMN place_source_evidence_runs.source_urls IS 'JSONB array of URLs fetched (allowed: debug metadata)';
COMMENT ON COLUMN place_source_evidence_runs.source_evidence IS 'JSONB evidence content (allowed: evidence storage)';
COMMENT ON COLUMN place_source_evidence_runs.evidence_markers IS 'JSONB trust markers (allowed: evidence storage)';

-- ----------------------------------------------------------------------------
-- 2.3 place_google_sources: Google Places API cache (Vendor source family)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS place_google_sources (
    id bigserial PRIMARY KEY,
    place_id bigint NOT NULL,
    google_place_id text NOT NULL,
    name text,
    formatted_address text,
    phone text,
    website text,
    rating numeric(2,1) CHECK (rating >= 0 AND rating <= 5),
    review_count integer DEFAULT 0 CHECK (review_count >= 0),
    business_status text,
    lat numeric(10,8),
    lon numeric(11,8),
    raw_payload jsonb,
    fetched_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz,
    is_current boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    
    -- Foreign key to places table
    CONSTRAINT fk_google_sources_place 
        FOREIGN KEY (place_id) REFERENCES places(id) ON DELETE CASCADE,
    
    -- Ensure unique google_place_id per place
    CONSTRAINT uq_place_google_sources_place_google_id 
        UNIQUE (place_id, google_place_id)
);

COMMENT ON TABLE place_google_sources IS 
    'Google Places API cache - Vendor source family per Source-Completeness Rule';
COMMENT ON COLUMN place_google_sources.place_id IS 'Reference to places.id';
COMMENT ON COLUMN place_google_sources.google_place_id IS 'Google Places API place_id';
COMMENT ON COLUMN place_google_sources.raw_payload IS 'Full Google Places API response (allowed: vendor-specific)';
COMMENT ON COLUMN place_google_sources.fetched_at IS 'When data was fetched from Google';
COMMENT ON COLUMN place_google_sources.expires_at IS 'Cache expiration time';
COMMENT ON COLUMN place_google_sources.is_current IS 'Whether this is the current valid source record';

-- ============================================================================
-- PART 3: Create Child Tables for LLM Enrichments
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 3.1 place_llm_facts: Individual facts extracted by LLM
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS place_llm_facts (
    id bigserial PRIMARY KEY,
    llm_enrichment_id bigint NOT NULL,
    field_name text NOT NULL,
    value_text text,
    value_type text NOT NULL DEFAULT 'string' 
        CHECK (value_type IN ('string', 'boolean', 'number', 'array', 'object')),
    confidence numeric(3,2) CHECK (confidence >= 0 AND confidence <= 1),
    provenance_kind text DEFAULT 'llm_extracted' 
        CHECK (provenance_kind IN ('llm_extracted', 'source_verified', 'user_confirmed')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    
    -- Foreign key to parent table
    CONSTRAINT fk_llm_facts_enrichment 
        FOREIGN KEY (llm_enrichment_id) REFERENCES place_llm_enrichments(id) ON DELETE CASCADE
);

COMMENT ON TABLE place_llm_facts IS 
    'Individual facts extracted by LLM - Per Amenity Facts Pattern (hard facts in typed columns)';
COMMENT ON COLUMN place_llm_facts.llm_enrichment_id IS 'Reference to place_llm_enrichments.id';
COMMENT ON COLUMN place_llm_facts.field_name IS 'Name of the field (e.g., has_electricity, phone)';
COMMENT ON COLUMN place_llm_facts.value_text IS 'Value as text (parsed based on value_type)';
COMMENT ON COLUMN place_llm_facts.value_type IS 'Data type of the value';
COMMENT ON COLUMN place_llm_facts.provenance_kind IS 'How this fact was derived';

-- ----------------------------------------------------------------------------
-- 3.2 place_llm_sources: Sources cited by LLM
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS place_llm_sources (
    id bigserial PRIMARY KEY,
    llm_enrichment_id bigint NOT NULL,
    source_url text NOT NULL,
    source_domain text,
    source_kind text NOT NULL DEFAULT 'website' 
        CHECK (source_kind IN ('website', 'google_reviews', 'osm', 'user_submission', 'other')),
    trusted boolean DEFAULT false,
    relevance_score numeric(3,2) CHECK (relevance_score >= 0 AND relevance_score <= 1),
    fetched_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    
    -- Foreign key to parent table
    CONSTRAINT fk_llm_sources_enrichment 
        FOREIGN KEY (llm_enrichment_id) REFERENCES place_llm_enrichments(id) ON DELETE CASCADE
);

COMMENT ON TABLE place_llm_sources IS 
    'Sources cited by LLM during enrichment';
COMMENT ON COLUMN place_llm_sources.llm_enrichment_id IS 'Reference to place_llm_enrichments.id';
COMMENT ON COLUMN place_llm_sources.source_url IS 'Full URL of the source';
COMMENT ON COLUMN place_llm_sources.source_domain IS 'Domain extracted from URL';
COMMENT ON COLUMN place_llm_sources.source_kind IS 'Type of source';
COMMENT ON COLUMN place_llm_sources.trusted IS 'Whether source is in trusted domains list';

-- ----------------------------------------------------------------------------
-- 3.3 place_llm_evidence_markers: Trust markers for LLM output
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS place_llm_evidence_markers (
    id bigserial PRIMARY KEY,
    llm_enrichment_id bigint NOT NULL,
    field_name text NOT NULL,
    marker_text text NOT NULL,
    marker_type text NOT NULL DEFAULT 'citation' 
        CHECK (marker_type IN ('citation', 'quote', 'summary', 'confidence')),
    confidence numeric(3,2) CHECK (confidence >= 0 AND confidence <= 1),
    created_at timestamptz NOT NULL DEFAULT now(),
    
    -- Foreign key to parent table
    CONSTRAINT fk_llm_evidence_enrichment 
        FOREIGN KEY (llm_enrichment_id) REFERENCES place_llm_enrichments(id) ON DELETE CASCADE
);

COMMENT ON TABLE place_llm_evidence_markers IS 
    'Trust markers and citations for LLM output';
COMMENT ON COLUMN place_llm_evidence_markers.llm_enrichment_id IS 'Reference to place_llm_enrichments.id';
COMMENT ON COLUMN place_llm_evidence_markers.field_name IS 'Field this marker relates to';
COMMENT ON COLUMN place_llm_evidence_markers.marker_text IS 'The marker text (quote or citation)';
COMMENT ON COLUMN place_llm_evidence_markers.marker_type IS 'Type of evidence marker';

-- ============================================================================
-- PART 4: Create Child Tables for Evidence Collection Runs
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 4.1 place_evidence_sources: Sources fetched during evidence collection
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS place_evidence_sources (
    id bigserial PRIMARY KEY,
    evidence_run_id bigint NOT NULL,
    source_url text NOT NULL,
    source_domain text,
    fetch_status text NOT NULL DEFAULT 'pending' 
        CHECK (fetch_status IN ('pending', 'fetching', 'success', 'failed', 'timeout', 'blocked')),
    http_status integer,
    trusted boolean DEFAULT false,
    content_type text,
    fetched_at timestamptz,
    content_length integer,
    error_message text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    
    -- Foreign key to parent table
    CONSTRAINT fk_evidence_sources_run 
        FOREIGN KEY (evidence_run_id) REFERENCES place_source_evidence_runs(id) ON DELETE CASCADE
);

COMMENT ON TABLE place_evidence_sources IS 
    'Individual sources fetched during evidence collection';
COMMENT ON COLUMN place_evidence_sources.evidence_run_id IS 'Reference to place_source_evidence_runs.id';
COMMENT ON COLUMN place_evidence_sources.source_url IS 'URL that was fetched';
COMMENT ON COLUMN place_evidence_sources.fetch_status IS 'Status of the fetch operation';
COMMENT ON COLUMN place_evidence_sources.http_status IS 'HTTP response code';
COMMENT ON COLUMN place_evidence_sources.trusted IS 'Whether domain is in trusted list';

-- ----------------------------------------------------------------------------
-- 4.2 place_evidence_markers: Evidence markers from collection
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS place_evidence_markers (
    id bigserial PRIMARY KEY,
    evidence_run_id bigint NOT NULL,
    field_name text NOT NULL,
    marker_text text NOT NULL,
    marker_type text NOT NULL DEFAULT 'extract' 
        CHECK (marker_type IN ('extract', 'quote', 'summary', 'pattern_match')),
    confidence numeric(3,2) CHECK (confidence >= 0 AND confidence <= 1),
    source_url text,
    context_before text,
    context_after text,
    created_at timestamptz NOT NULL DEFAULT now(),
    
    -- Foreign key to parent table
    CONSTRAINT fk_evidence_markers_run 
        FOREIGN KEY (evidence_run_id) REFERENCES place_source_evidence_runs(id) ON DELETE CASCADE
);

COMMENT ON TABLE place_evidence_markers IS 
    'Evidence markers extracted from sources during collection';
COMMENT ON COLUMN place_evidence_markers.evidence_run_id IS 'Reference to place_source_evidence_runs.id';
COMMENT ON COLUMN place_evidence_markers.field_name IS 'Field this evidence supports';
COMMENT ON COLUMN place_evidence_markers.marker_text IS 'The evidence text';
COMMENT ON COLUMN place_evidence_markers.source_url IS 'URL where evidence was found';
COMMENT ON COLUMN place_evidence_markers.context_before IS 'Text before marker for context';
COMMENT ON COLUMN place_evidence_markers.context_after IS 'Text after marker for context';

-- ============================================================================
-- PART 5: Create Child Tables for Google Sources
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 5.1 place_google_reviews: Individual Google reviews
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS place_google_reviews (
    id bigserial PRIMARY KEY,
    google_source_id bigint NOT NULL,
    author_name text,
    rating integer CHECK (rating >= 1 AND rating <= 5),
    language_code text,
    review_text text,
    review_time timestamptz,
    relative_time_description text,
    google_review_id text,
    created_at timestamptz NOT NULL DEFAULT now(),
    
    -- Foreign key to parent table
    CONSTRAINT fk_google_reviews_source 
        FOREIGN KEY (google_source_id) REFERENCES place_google_sources(id) ON DELETE CASCADE,
    
    -- Ensure unique review per source
    CONSTRAINT uq_google_reviews_source_review_id 
        UNIQUE (google_source_id, google_review_id)
);

COMMENT ON TABLE place_google_reviews IS 
    'Individual Google reviews extracted from API response';
COMMENT ON COLUMN place_google_reviews.google_source_id IS 'Reference to place_google_sources.id';
COMMENT ON COLUMN place_google_reviews.google_review_id IS 'Original review ID from Google';
COMMENT ON COLUMN place_google_reviews.review_time IS 'When review was posted';

-- ----------------------------------------------------------------------------
-- 5.2 place_google_photos: Google place photos
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS place_google_photos (
    id bigserial PRIMARY KEY,
    google_source_id bigint NOT NULL,
    photo_reference text NOT NULL,
    width integer,
    height integer,
    attribution text,
    google_photo_id text,
    created_at timestamptz NOT NULL DEFAULT now(),
    
    -- Foreign key to parent table
    CONSTRAINT fk_google_photos_source 
        FOREIGN KEY (google_source_id) REFERENCES place_google_sources(id) ON DELETE CASCADE,
    
    -- Ensure unique photo per source
    CONSTRAINT uq_google_photos_source_photo_ref 
        UNIQUE (google_source_id, photo_reference)
);

COMMENT ON TABLE place_google_photos IS 
    'Google place photos metadata';
COMMENT ON COLUMN place_google_photos.google_source_id IS 'Reference to place_google_sources.id';
COMMENT ON COLUMN place_google_photos.photo_reference IS 'Google photo reference token';
COMMENT ON COLUMN place_google_photos.attribution IS 'Photo attribution text';

-- ----------------------------------------------------------------------------
-- 5.3 place_google_types: Google place types/categories
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS place_google_types (
    id bigserial PRIMARY KEY,
    google_source_id bigint NOT NULL,
    google_type text NOT NULL,
    is_primary boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    
    -- Foreign key to parent table
    CONSTRAINT fk_google_types_source 
        FOREIGN KEY (google_source_id) REFERENCES place_google_sources(id) ON DELETE CASCADE,
    
    -- Ensure unique type per source
    CONSTRAINT uq_google_types_source_type 
        UNIQUE (google_source_id, google_type)
);

COMMENT ON TABLE place_google_types IS 
    'Google place types (categories) for the location';
COMMENT ON COLUMN place_google_types.google_source_id IS 'Reference to place_google_sources.id';
COMMENT ON COLUMN place_google_types.google_type IS 'Google Places API type (e.g., campground, rv_park)';
COMMENT ON COLUMN place_google_types.is_primary IS 'Whether this is the primary type';

-- ============================================================================
-- PART 6: Create Indexes for Common Query Patterns
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 6.1 Indexes for place_llm_enrichments
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_llm_enrichments_place_id 
    ON place_llm_enrichments(place_id);
CREATE INDEX IF NOT EXISTS idx_llm_enrichments_job_id 
    ON place_llm_enrichments(job_id) WHERE job_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_llm_enrichments_status 
    ON place_llm_enrichments(status);
CREATE INDEX IF NOT EXISTS idx_llm_enrichments_is_current 
    ON place_llm_enrichments(is_current) WHERE is_current = true;
CREATE INDEX IF NOT EXISTS idx_llm_enrichments_place_is_current 
    ON place_llm_enrichments(place_id, is_current) WHERE is_current = true;
CREATE INDEX IF NOT EXISTS idx_llm_enrichments_provider 
    ON place_llm_enrichments(provider);
CREATE INDEX IF NOT EXISTS idx_llm_enrichments_created_at 
    ON place_llm_enrichments(created_at DESC);

-- ----------------------------------------------------------------------------
-- 6.2 Indexes for place_source_evidence_runs
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_evidence_runs_place_id 
    ON place_source_evidence_runs(place_id);
CREATE INDEX IF NOT EXISTS idx_evidence_runs_job_id 
    ON place_source_evidence_runs(job_id) WHERE job_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_evidence_runs_status 
    ON place_source_evidence_runs(collection_status);
CREATE INDEX IF NOT EXISTS idx_evidence_runs_worker_id 
    ON place_source_evidence_runs(worker_id) WHERE worker_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_evidence_runs_created_at 
    ON place_source_evidence_runs(created_at DESC);

-- ----------------------------------------------------------------------------
-- 6.3 Indexes for place_google_sources
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_google_sources_place_id 
    ON place_google_sources(place_id);
CREATE INDEX IF NOT EXISTS idx_google_sources_google_place_id 
    ON place_google_sources(google_place_id);
CREATE INDEX IF NOT EXISTS idx_google_sources_is_current 
    ON place_google_sources(is_current) WHERE is_current = true;
CREATE INDEX IF NOT EXISTS idx_google_sources_place_is_current 
    ON place_google_sources(place_id, is_current) WHERE is_current = true;
CREATE INDEX IF NOT EXISTS idx_google_sources_expires_at 
    ON place_google_sources(expires_at) WHERE expires_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_google_sources_rating 
    ON place_google_sources(rating) WHERE rating IS NOT NULL;

-- ----------------------------------------------------------------------------
-- 6.4 Indexes for child tables (LLM facts)
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_llm_facts_enrichment_id 
    ON place_llm_facts(llm_enrichment_id);
CREATE INDEX IF NOT EXISTS idx_llm_facts_field_name 
    ON place_llm_facts(field_name);
CREATE INDEX IF NOT EXISTS idx_llm_facts_confidence 
    ON place_llm_facts(confidence) WHERE confidence IS NOT NULL;

-- ----------------------------------------------------------------------------
-- 6.5 Indexes for child tables (LLM sources)
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_llm_sources_enrichment_id 
    ON place_llm_sources(llm_enrichment_id);
CREATE INDEX IF NOT EXISTS idx_llm_sources_trusted 
    ON place_llm_sources(trusted) WHERE trusted = true;
CREATE INDEX IF NOT EXISTS idx_llm_sources_domain 
    ON place_llm_sources(source_domain) WHERE source_domain IS NOT NULL;

-- ----------------------------------------------------------------------------
-- 6.6 Indexes for child tables (LLM evidence markers)
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_llm_evidence_enrichment_id 
    ON place_llm_evidence_markers(llm_enrichment_id);
CREATE INDEX IF NOT EXISTS idx_llm_evidence_field_name 
    ON place_llm_evidence_markers(field_name);

-- ----------------------------------------------------------------------------
-- 6.7 Indexes for child tables (evidence sources)
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_evidence_sources_run_id 
    ON place_evidence_sources(evidence_run_id);
CREATE INDEX IF NOT EXISTS idx_evidence_sources_status 
    ON place_evidence_sources(fetch_status);
CREATE INDEX IF NOT EXISTS idx_evidence_sources_trusted 
    ON place_evidence_sources(trusted) WHERE trusted = true;

-- ----------------------------------------------------------------------------
-- 6.8 Indexes for child tables (evidence markers)
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_evidence_markers_run_id 
    ON place_evidence_markers(evidence_run_id);
CREATE INDEX IF NOT EXISTS idx_evidence_markers_field_name 
    ON place_evidence_markers(field_name);

-- ----------------------------------------------------------------------------
-- 6.9 Indexes for child tables (Google reviews)
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_google_reviews_source_id 
    ON place_google_reviews(google_source_id);
CREATE INDEX IF NOT EXISTS idx_google_reviews_rating 
    ON place_google_reviews(rating) WHERE rating IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_google_reviews_time 
    ON place_google_reviews(review_time DESC) WHERE review_time IS NOT NULL;

-- ----------------------------------------------------------------------------
-- 6.10 Indexes for child tables (Google photos)
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_google_photos_source_id 
    ON place_google_photos(google_source_id);

-- ----------------------------------------------------------------------------
-- 6.11 Indexes for child tables (Google types)
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_google_types_source_id 
    ON place_google_types(google_source_id);
CREATE INDEX IF NOT EXISTS idx_google_types_is_primary 
    ON place_google_types(is_primary) WHERE is_primary = true;

-- ----------------------------------------------------------------------------
-- 6.12 Indexes for new place_enrichment columns
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_place_enrichment_collection_status 
    ON place_enrichment(collection_status) WHERE collection_status IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_place_enrichment_failure_classification 
    ON place_enrichment(failure_classification) WHERE failure_classification IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_place_enrichment_schema_version 
    ON place_enrichment(enrichment_schema_version) WHERE enrichment_schema_version IS NOT NULL;

-- ============================================================================
-- PART 7: Create Auto-Update Triggers for updated_at
-- ============================================================================

-- Function to auto-update updated_at column
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply to all tables with updated_at
DO $$
DECLARE
    tbl text;
    tables text[] := ARRAY[
        'place_llm_enrichments',
        'place_source_evidence_runs',
        'place_google_sources',
        'place_llm_facts',
        'place_llm_sources',
        'place_evidence_sources',
        'place_evidence_markers'
    ];
BEGIN
    FOREACH tbl IN ARRAY tables
    LOOP
        EXECUTE format(
            'DROP TRIGGER IF EXISTS trg_%I_updated_at ON %I;',
            tbl, tbl
        );
        EXECUTE format(
            'CREATE TRIGGER trg_%I_updated_at
             BEFORE UPDATE ON %I
             FOR EACH ROW
             EXECUTE FUNCTION update_updated_at_column();',
            tbl, tbl
        );
    END LOOP;
END;
$$;

-- ============================================================================
-- PART 8: Enable Row Level Security
-- ============================================================================

-- Enable RLS on all new tables
ALTER TABLE place_llm_enrichments ENABLE ROW LEVEL SECURITY;
ALTER TABLE place_source_evidence_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE place_google_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE place_llm_facts ENABLE ROW LEVEL SECURITY;
ALTER TABLE place_llm_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE place_llm_evidence_markers ENABLE ROW LEVEL SECURITY;
ALTER TABLE place_evidence_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE place_evidence_markers ENABLE ROW LEVEL SECURITY;
ALTER TABLE place_google_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE place_google_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE place_google_types ENABLE ROW LEVEL SECURITY;

-- Create restrictive policies (service role only for now)
-- These can be relaxed later when user access patterns are defined

CREATE POLICY "Service role can manage LLM enrichments"
    ON place_llm_enrichments FOR ALL
    USING (false)
    WITH CHECK (false);

CREATE POLICY "Service role can manage evidence runs"
    ON place_source_evidence_runs FOR ALL
    USING (false)
    WITH CHECK (false);

CREATE POLICY "Service role can manage Google sources"
    ON place_google_sources FOR ALL
    USING (false)
    WITH CHECK (false);

CREATE POLICY "Service role can manage LLM facts"
    ON place_llm_facts FOR ALL
    USING (false)
    WITH CHECK (false);

CREATE POLICY "Service role can manage LLM sources"
    ON place_llm_sources FOR ALL
    USING (false)
    WITH CHECK (false);

CREATE POLICY "Service role can manage LLM evidence markers"
    ON place_llm_evidence_markers FOR ALL
    USING (false)
    WITH CHECK (false);

CREATE POLICY "Service role can manage evidence sources"
    ON place_evidence_sources FOR ALL
    USING (false)
    WITH CHECK (false);

CREATE POLICY "Service role can manage evidence markers"
    ON place_evidence_markers FOR ALL
    USING (false)
    WITH CHECK (false);

CREATE POLICY "Service role can manage Google reviews"
    ON place_google_reviews FOR ALL
    USING (false)
    WITH CHECK (false);

CREATE POLICY "Service role can manage Google photos"
    ON place_google_photos FOR ALL
    USING (false)
    WITH CHECK (false);

CREATE POLICY "Service role can manage Google types"
    ON place_google_types FOR ALL
    USING (false)
    WITH CHECK (false);

-- ============================================================================
-- PART 9: Verification Queries (for post-migration validation)
-- ============================================================================

-- Uncomment to verify after migration:
-- 
-- -- Check new columns on place_enrichment
-- SELECT column_name, data_type 
-- FROM information_schema.columns 
-- WHERE table_name = 'place_enrichment' 
-- AND column_name IN ('source_evidence', 'evidence_markers', 'collection_status', 
--                     'failure_classification', 'provider_attempts', 'job_cost_usd', 
--                     'enrichment_schema_version')
-- ORDER BY ordinal_position;
-- 
-- -- Check all new tables exist
-- SELECT table_name 
-- FROM information_schema.tables 
-- WHERE table_schema = 'public' 
-- AND table_name IN (
--     'place_llm_enrichments',
--     'place_llm_facts',
--     'place_llm_sources',
--     'place_llm_evidence_markers',
--     'place_source_evidence_runs',
--     'place_evidence_sources',
--     'place_evidence_markers',
--     'place_google_sources',
--     'place_google_reviews',
--     'place_google_photos',
--     'place_google_types'
-- )
-- ORDER BY table_name;
-- 
-- -- Check foreign keys
-- SELECT
--     tc.table_name,
--     kcu.column_name,
--     ccu.table_name AS foreign_table_name,
--     ccu.column_name AS foreign_column_name
-- FROM information_schema.table_constraints tc
-- JOIN information_schema.key_column_usage kcu
--     ON tc.constraint_name = kcu.constraint_name
-- JOIN information_schema.constraint_column_usage ccu
--     ON ccu.constraint_name = tc.constraint_name
-- WHERE tc.constraint_type = 'FOREIGN KEY'
-- AND tc.table_name LIKE 'place_%';
